# Node 1 — Local testing config
node_id: 1
listen_port: 50051
data_dir: "./data/node1"

heartbeat_interval_ms: 200
heartbeat_timeout_ms: 300
election_timeout_ms: 200
replication_factor: 2
checkpoint_interval: 500

peers:
  - id: 2
    address: "10.12.227.43:50051"
  - id: 3
    address: "10.12.235.25:50051"
  - id: 4
    address: "10.12.227.43:50051"
